### ISSUE TITLE
Missing vagrant-bootstrap.sh

### ISSUE THREAD

**Issue by syheliel** [MCUSec/SEmu#1]
In your README, you mentioned there is a file in : https://github.com/MCUSec/SEmu/blob/main/vagrant-bootstrap.sh

But it is not avaliable now

**Comment by weizhou-chaojixx** [comment]
Thanks for pointing this mistake. This file is in other repo https://github.com/MCUSec/uEmu/blob/main/vagrant-bootstrap.sh#L8. I have also fixed this link in the Readme.
