### ISSUE TITLE
The installation process for the tagger and parser components is too brief.

### ISSUE THREAD

**Issue by F01ivor4** [MCUSec/SEmu#2]
The README does not mention which version of files to install, but the version numbers are hardcoded in the related Python scripts. So, I downloaded and extracted`stanford-postagger-full-2020-08-06` and `stanford-parser-4.0.0`. However, when I run the program, I get an error message 
```
LookupError: Could not find stanford-parser.jar jar file at ./models/stanford-parser-4.0.0/stanford-corenlp-4.4.0.jar
```
After I downloaded the corresponding version of stanford-corenlp and moved the files to the appropriate folders, I encountered another error message
```
java.io.IOException: Unable to open "./models/stanford-parser-4.0.0/stanford-parser-4.0.0-models/edu/stanford/nlp/models/lexparser/englishPCFG4.4.0.ser.gz as class path, filename or URL
```
 I checked the relevant paths and files and found that my files only have "englishPCFG.ser.gz". I believe the related paths are too fixed, and the README is too brief regarding the installation instructions. Please provide more relevant information.

**Comment by Moirai7** [comment]
Thanks for reaching out!
Stanford models have been uploaded to google drive(https://drive.google.com/file/d/1ZoIL5lQMNPykCb4axHseqRxGbjw7S2x2/view?usp=sharing). You may need to download it and unzip it to models.
Also, please pull the commits to use those models.
