### ISSUE TITLE
crash when using ./launch-SEmu.sh

### ISSUE THREAD

**Issue by Wi1L-Y** [MCUSec/SEmu#3]
I try to generate "./launch-SEmu.sh" with " python3 SEmu-helper.py K64F-RIOT-ADC.elf K64F_adc.cfg -rule k64.txt" and " python3 SEmu-helper.py K64F-RIOT-ADC.elf K64F_adc.cfg -rule ADC.txt", but both of the scripts ( ./launch-SEmu.sh) are failed when running. The information is as follows:
   "
Starting libs2e...
Opening /dev/kvm
Using module /home/u18041/Desktop/SEmu//build/libs2e-release/arm-s2e-softmmu/op_helper.bc.arm
S2E: output directory = "./s2e-out-2"
Using log level override 'warn'
Setting console level to 'warn'
QEMU 3.0.0 monitor - type 'help' for more information
(qemu) Adding rom 0x0 baseaddr:0x0 size:0x40000
Only 1 rom has been configured
Adding ram 0x0 baseaddr:0x1ffe0000 size:0x60000
Only 1 ram has been configured
Adding CPU (addr = 0x7f2a44009f00, size = 0x36bc8)
vecbase=0
No init.entry given
No init.msp given
init firmware pc entry = 0 msp_init = 0 vtor = 0
 entry = 0x0 vecbase = 0x0 msp_init = 0x0 ret = 0
vecbase=0
vecbase=0
No init.entry given
No init.msp given
init firmware pc entry = 0 msp_init = 0 vtor = 0
 entry = 0x0 vecbase = 0x0 msp_init = 0x0 ret = 0
vecbase=0
vecbase=0
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
./launch-SEmu.sh: line 84: 109590 Aborted                 (core dumped) LD_PRELOAD=$LIBS2E $QEMU -k en-us $GRAPHICS -M mps2-ans2e -cpu cortex-m3 -m $QEMU_MEMORY -enable-kvm -serial file:s2e-last/serial.txt $QEMU_EXTRA_FLAGS -kernel $FIRMWARE
"

I search the error "terminate called after throwing an instance of 'std::logic_error'   what():  basic_string::_M_construct null not valid", but  
 I don't know why it crashes about the project.
Is this because of a problem with my operation

**Comment by weizhou-chaojixx** [comment]
Thanks for bringing up this issue to us, I will try to reproduce this problems these days and reply later on.

**Comment by weizhou-chaojixx** [comment]
Sorry for updating the out-of-date K64 rule file in the dataset, please use the latest rule file [here](https://github.com/MCUSec/SEmu/blob/main/RuleExtraction/extractedRules/k64.txt), and also please git pull the library LUA [file](https://github.com/MCUSec/SEmu/blob/main/SymDiagnose/Scripts/library.lua) when you run the "/launch-SEmu.sh" scrip[t.

**Comment by Wi1L-Y** [comment]
Thank you for your reply. I have solved the problem by replacing the rule file when debugging the libs2e.so before and forgot to commit. Thanks.
