### ISSUE TITLE
“python extract.py k64 UART” 

### ISSUE THREAD

**Issue by B1y0nd** [MCUSec/SEmu#4]
I try to run “python extract.py k64 UART”，but the error appeared. The detailed info is as follows:
![error](https://user-images.githubusercontent.com/130897325/234263660-d623aba5-dcf0-4d91-b8cd-a782bc117bf1.png)
When the parameter is set "python extract.py k64 UART", I try to print the info `self.txt.registers[tmp]`.
Then, the results are shown below.
![result](https://user-images.githubusercontent.com/130897325/234264861-9e24d281-09b1-44eb-aa0c-c5635ad353ab.png)
I don't think you deal with the situation without 'B'.

**Comment by Wi1L-Y** [comment]
I also encountered this problem, changed a peripheral and ran successfully, but did not fundamentally solve this problem, and still need to analyze the source code.

**Comment by Moirai7** [comment]
Thanks for posting the issue! I have updated the code.

**Comment by B1y0nd** [comment]
> I also encountered this problem, changed a peripheral and ran successfully, but did not fundamentally solve this problem, and still need to analyze the source code.

Yes. It seems that only UART will report an error.
