### ISSUE TITLE
linux-headers/asm/kvm.h:25:10: fatal error: asm/ptracearm.h: No such file or directory

### ISSUE THREAD

**Issue by B1y0nd** [MCUSec/SEmu#5]
I met a problem. 
when I ran "make -f $SEmuDIR/Makefile && make -f $SEmuDIR/Makefile install"，the error appeared. The detailed info is as follows:
![Snipaste_2023-04-29_15-58-53](https://user-images.githubusercontent.com/130897325/235291804-ef8bc90e-34aa-4c65-adc9-26cb85919f75.png)
After searching for some info, I feel that this is not your code problem. I don't know if you have encountered this issue during the compilation process.

**Comment by weizhou-chaojixx** [comment]
Sorry for forgetting upload this file, you can download this [file](https://github.com/MCUSec/uEmu/blob/main/ptracearm.h) from our uEmu repo which is same with SEmu.

**Comment by B1y0nd** [comment]
> 

Thanks.
